### ISSUE TITLE
does not work in proxy

### ISSUE THREAD

**Issue by kanxg** [leancloud/java-sdk#8]
你们的文档没有说明是否支持代理访问， 从gogole上看到有客服说不支持。
但你们的代码PaasClient 中的 AVHttpClient是支持代理的，但这个对象是private。
我只有拷贝类PaasClient 出来，把AVHttpClient改成public
然后设置PaasClient.client.setProxy(）, 才能work。
需要你们修改代码来支持代理。

**Comment by lbt05** [comment]
由于我们仅仅限定了 LeanCloud 的 API 访问的 endpoint ，出于安全考虑，不准备开放proxy功能。如确实有这方面的需求，推荐 fork 一个 repository即可
